import Head from "next/head";

export default function CustomizedHead() {
  return (
    <Head>
      <title>Favorite dogs</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>)
}